version: "3"
services:
    web:
        build:
          context: .
          args:
            - buildConfig=Release
        volumes:
            - ./src/DddMelb2019.Web/wwwroot:/app/wwwroot
        ports:
            - "4002:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Release 
            - DOTNET_USE_POLLING_FILE_WATCHER=true
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Password12345!"
            ACCEPT_EULA: "Y"